{% set name = "PhiK" %}
{% set version = "0.11.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/KaveIO/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: e98e6078b8c81165c6ad565b933883bda8370a375936c478f2d733bcd67863a8

build:
  number: 0
  noarch: python
  entry_points:
    - phik_trial = phik.entry_points:phik_trial  # [win]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - numpy >=1.15.4
    - scipy >=1.1.0
    - pandas >=0.23.4
    - matplotlib-base >=2.2.3
    - numba >=0.38.1
    - joblib >=0.14.1

test:
  imports:
    - phik

about:
  home: https://github.com/KaveIO/PhiK
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Phi_K correlation analyzer library
  description: |
    Phi_K is a new and practical correlation coefficient based on several
    refinements to Pearson's hypothesis test of independence of two variables.
  doc_url: http://phik.readthedocs.io/
  dev_url: https://github.com/KaveIO/PhiK

extra:
  recipe-maintainers:
    - philip-khor
