{% set name = "PhiK" %}
{% set version = "0.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/KaveIO/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 58b5ba2dab0ce30ff171551141b06dd1724611ccdd4654c285d1bece76e6ad6a

build:
  number: 0
  entry_points:
    - phik_trial = phik.entry_points:phik_trial  # [win]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake >=3.14
  host:
    - python
    - pip
    - pybind11
    - pybind11-abi
    - pybind11-stubgen
  run:
    - python
    - numpy >=1.18.0
    - scipy >=1.5.2
    - pandas >=0.25.1
    - matplotlib-base >=2.2.3
    - joblib >=0.14.1


test:
  imports:
    - phik

about:
  home: https://github.com/KaveIO/PhiK
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Phi_K correlation analyzer library
  description: |
    Phi_K is a new and practical correlation coefficient based on several
    refinements to Pearson's hypothesis test of independence of two variables.
  doc_url: http://phik.readthedocs.io/
  dev_url: https://github.com/KaveIO/PhiK

extra:
  recipe-maintainers:
    - philip-khor
