context:
  name: "PhiK"
  version: "0.12.4"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/phik-${{ version }}.tar.gz
  sha256: d4d53274685e56fb08088505b4eec70be07f2f8044e7961ca02b399e42c37025

build:
  number: 0
  # entry_points:
  # - phik_trial = phik.entry_points:phik_trial # [win]
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ stdlib("c") }}
    - cmake >=3.16
    - if: unix
      then: ninja
    - if: target_platform == 'linux-64'
      then: make
    - if: build_platform != target_platform
      then: python
    - if: build_platform != target_platform
      then: numpy
    - if: build_platform != target_platform
      then: cross-python_${{ target_platform }}
    - if: build_platform != target_platform
      then: make
  host:
    - python
    - scikit-build-core >=0.3.3
    - pybind11
    - pip
  run:
    - python
    - numpy >=1.18.0
    - scipy >=1.5.2
    - pandas >=0.25.1
    - matplotlib-base >=2.2.3
    - joblib >=0.14.1
tests:
  - python:
      imports:
        - phik

about:
  homepage: https://github.com/KaveIO/PhiK
  license: Apache-2.0
  license_file: LICENSE
  summary: Phi_K correlation analyzer library
  description: |
    Phi_K is a new and practical correlation coefficient based on several
    refinements to Pearson's hypothesis test of independence of two variables.
  documentation: http://phik.readthedocs.io/
  repository: https://github.com/KaveIO/PhiK

extra:
  recipe-maintainers:
    - philip-khor
